### ISSUE TITLE
Takedown

### ISSUE THREAD

**Issue by Mar0xy** [VHSgunzo/sr_patch#1]
Please take this down as even just sharing the zip with a obvious repo name such as sr_patch already ruins it for everyone else and if people want it then they should search for it themselves as there are only 2 official repos for this patch with one being a mirror.

also do not come with did you read the rules we work with the patch author and reuploading is sharing.

**Comment by VHSgunzo** [comment]
Your [project](https://github.com/an-anime-team/the-honkers-railway-launcher) is much more noticeable and more obviously refers to the game than this unnamed repository without any description, so I will close this repository only after you close your project.
